// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CheckDiscriminator is an autogenerated mock type for the CheckDiscriminator type
type CheckDiscriminator struct {
	mock.Mock
}

type CheckDiscriminator_Expecter struct {
	mock *mock.Mock
}

func (_m *CheckDiscriminator) EXPECT() *CheckDiscriminator_Expecter {
	return &CheckDiscriminator_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewCheckDiscriminator interface {
	mock.TestingT
	Cleanup(func())
}

// NewCheckDiscriminator creates a new instance of CheckDiscriminator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCheckDiscriminator(t mockConstructorTestingTNewCheckDiscriminator) *CheckDiscriminator {
	mock := &CheckDiscriminator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
