// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Doer is an autogenerated mock type for the Doer type
type Doer struct {
	mock.Mock
}

type Doer_Expecter struct {
	mock *mock.Mock
}

func (_m *Doer) EXPECT() *Doer_Expecter {
	return &Doer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: _a0
func (_m *Doer) Do(_a0 *http.Request) (*http.Response, error) {
	ret := _m.Called(_a0)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Doer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type Doer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//  - _a0 *http.Request
func (_e *Doer_Expecter) Do(_a0 interface{}) *Doer_Do_Call {
	return &Doer_Do_Call{Call: _e.mock.On("Do", _a0)}
}

func (_c *Doer_Do_Call) Run(run func(_a0 *http.Request)) *Doer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *Doer_Do_Call) Return(_a0 *http.Response, _a1 error) *Doer_Do_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewDoer interface {
	mock.TestingT
	Cleanup(func())
}

// NewDoer creates a new instance of Doer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDoer(t mockConstructorTestingTNewDoer) *Doer {
	mock := &Doer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
