// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExportTemplateJSONBody is an autogenerated mock type for the ExportTemplateJSONBody type
type ExportTemplateJSONBody struct {
	mock.Mock
}

type ExportTemplateJSONBody_Expecter struct {
	mock *mock.Mock
}

func (_m *ExportTemplateJSONBody) EXPECT() *ExportTemplateJSONBody_Expecter {
	return &ExportTemplateJSONBody_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewExportTemplateJSONBody interface {
	mock.TestingT
	Cleanup(func())
}

// NewExportTemplateJSONBody creates a new instance of ExportTemplateJSONBody. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExportTemplateJSONBody(t mockConstructorTestingTNewExportTemplateJSONBody) *ExportTemplateJSONBody {
	mock := &ExportTemplateJSONBody{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
