// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	middleware "github.com/go-openapi/runtime/middleware"
	kubernetes "github.com/mwinters-stuff/solar-zero-scrape-golang/api/restapi/operations/kubernetes"

	mock "github.com/stretchr/testify/mock"
)

// GetMetricsHandler is an autogenerated mock type for the GetMetricsHandler type
type GetMetricsHandler struct {
	mock.Mock
}

type GetMetricsHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *GetMetricsHandler) EXPECT() *GetMetricsHandler_Expecter {
	return &GetMetricsHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0
func (_m *GetMetricsHandler) Handle(_a0 kubernetes.GetMetricsParams) middleware.Responder {
	ret := _m.Called(_a0)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(kubernetes.GetMetricsParams) middleware.Responder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}

// GetMetricsHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type GetMetricsHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//  - _a0 kubernetes.GetMetricsParams
func (_e *GetMetricsHandler_Expecter) Handle(_a0 interface{}) *GetMetricsHandler_Handle_Call {
	return &GetMetricsHandler_Handle_Call{Call: _e.mock.On("Handle", _a0)}
}

func (_c *GetMetricsHandler_Handle_Call) Run(run func(_a0 kubernetes.GetMetricsParams)) *GetMetricsHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubernetes.GetMetricsParams))
	})
	return _c
}

func (_c *GetMetricsHandler_Handle_Call) Return(_a0 middleware.Responder) *GetMetricsHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewGetMetricsHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetMetricsHandler creates a new instance of GetMetricsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetMetricsHandler(t mockConstructorTestingTNewGetMetricsHandler) *GetMetricsHandler {
	mock := &GetMetricsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
