// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NotificationRuleDiscriminator is an autogenerated mock type for the NotificationRuleDiscriminator type
type NotificationRuleDiscriminator struct {
	mock.Mock
}

type NotificationRuleDiscriminator_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationRuleDiscriminator) EXPECT() *NotificationRuleDiscriminator_Expecter {
	return &NotificationRuleDiscriminator_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewNotificationRuleDiscriminator interface {
	mock.TestingT
	Cleanup(func())
}

// NewNotificationRuleDiscriminator creates a new instance of NotificationRuleDiscriminator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNotificationRuleDiscriminator(t mockConstructorTestingTNewNotificationRuleDiscriminator) *NotificationRuleDiscriminator {
	mock := &NotificationRuleDiscriminator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
