// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NotificationEndpointDiscriminator is an autogenerated mock type for the NotificationEndpointDiscriminator type
type NotificationEndpointDiscriminator struct {
	mock.Mock
}

type NotificationEndpointDiscriminator_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationEndpointDiscriminator) EXPECT() *NotificationEndpointDiscriminator_Expecter {
	return &NotificationEndpointDiscriminator_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewNotificationEndpointDiscriminator interface {
	mock.TestingT
	Cleanup(func())
}

// NewNotificationEndpointDiscriminator creates a new instance of NotificationEndpointDiscriminator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNotificationEndpointDiscriminator(t mockConstructorTestingTNewNotificationEndpointDiscriminator) *NotificationEndpointDiscriminator {
	mock := &NotificationEndpointDiscriminator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
