// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PropertyKey is an autogenerated mock type for the PropertyKey type
type PropertyKey struct {
	mock.Mock
}

type PropertyKey_Expecter struct {
	mock *mock.Mock
}

func (_m *PropertyKey) EXPECT() *PropertyKey_Expecter {
	return &PropertyKey_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewPropertyKey interface {
	mock.TestingT
	Cleanup(func())
}

// NewPropertyKey creates a new instance of PropertyKey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPropertyKey(t mockConstructorTestingTNewPropertyKey) *PropertyKey {
	mock := &PropertyKey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
