// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Threshold is an autogenerated mock type for the Threshold type
type Threshold struct {
	mock.Mock
}

type Threshold_Expecter struct {
	mock *mock.Mock
}

func (_m *Threshold) EXPECT() *Threshold_Expecter {
	return &Threshold_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewThreshold interface {
	mock.TestingT
	Cleanup(func())
}

// NewThreshold creates a new instance of Threshold. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewThreshold(t mockConstructorTestingTNewThreshold) *Threshold {
	mock := &Threshold{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
