// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VariableProperties is an autogenerated mock type for the VariableProperties type
type VariableProperties struct {
	mock.Mock
}

type VariableProperties_Expecter struct {
	mock *mock.Mock
}

func (_m *VariableProperties) EXPECT() *VariableProperties_Expecter {
	return &VariableProperties_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewVariableProperties interface {
	mock.TestingT
	Cleanup(func())
}

// NewVariableProperties creates a new instance of VariableProperties. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVariableProperties(t mockConstructorTestingTNewVariableProperties) *VariableProperties {
	mock := &VariableProperties{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
