// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ViewProperties is an autogenerated mock type for the ViewProperties type
type ViewProperties struct {
	mock.Mock
}

type ViewProperties_Expecter struct {
	mock *mock.Mock
}

func (_m *ViewProperties) EXPECT() *ViewProperties_Expecter {
	return &ViewProperties_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewViewProperties interface {
	mock.TestingT
	Cleanup(func())
}

// NewViewProperties creates a new instance of ViewProperties. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewViewProperties(t mockConstructorTestingTNewViewProperties) *ViewProperties {
	mock := &ViewProperties{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
