kind: pipeline
type: docker
name: default

steps:
- name: build-go
  image: golang
  commands:
  - go install github.com/stretchr/gorc
  - gorc test
  - go build -o solar-zero-scrape

- name: build-dev-docker-image
  image: plugins/docker
  settings:
    username: 
      from_secret: harbor-username
    password: 
      from_secret: harbor-password
    repo: harbor.winters.org.nz/library/solar-zero-scrape-dev
    registry: harbor.winters.org.nz
    tags: 
      - latest
      - 0.3.${DRONE_BUILD_NUMBER}-dev
  depends_on:
    - build-go
  when:
    event:
      include:
        - push
      exclude:
        - tag

- name: build-release-docker-image
  image: plugins/docker
  settings:
    username: 
      from_secret: harbor-username
    password: 
      from_secret: harbor-password
    repo: harbor.winters.org.nz/library/solar-zero-scrape
    registry: harbor.winters.org.nz
    tags: 
      - latest
      - ${DRONE_SEMVER_SHORT}
  depends_on:
    - build-go
  when:
    event:
      - tag

- name: version-release-chart
  image: harbor.winters.org.nz/hub-cache/mikefarah/yq:latest
  user: 0
  commands:
    - VERTAG=$${DRONE_SEMVER_SHORT}
    - echo "New Version $${VERTAG} for solar-zero-scrape"
    - yq -i ".version = \"$${VERTAG}\" | .appVersion = \"$${VERTAG}\"" "charts/solar-zero-scrape/Chart.yaml"
    - yq -i ".image.tag = \"$${VERTAG}\"" "charts/solar-zero-scrape/values.yaml"
    - cat "charts/solar-zero-scrape/Chart.yaml"
    - cat "charts/solar-zero-scrape/values.yaml"
  when:
    event:
      - tag

- name: build-release-chart
  user: 0
  image: harbor.winters.org.nz/hub-cache/library/ubuntu:20.04
  environment:
    HARBOR_PASSWORD:
      from_secret: harbor-password
    HARBOR_USERNAME:
      from_secret: harbor-username
  commands:
    - VERTAG=$${DRONE_SEMVER_SHORT}
    - env
    - apt-get update
    - apt-get install -y curl git
    - curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    - chmod 700 /tmp/get_helm.sh
    - /tmp/get_helm.sh
    - git config --global --add safe.directory $(pwd)
    - helm repo add --username "$${HARBOR_USERNAME}" --password "$${HARBOR_PASSWORD}" harbor https://harbor.winters.org.nz/chartrepo/library/ || exit 1
    - helm plugin install https://github.com/chartmuseum/helm-push || exit 1
    - helm package -u charts/solar-zero-scrape || exit 1
    - helm cm-push "solar-zero-scrape-$${VERTAG}.tgz" harbor || exit 1
  depends_on:
    - version-release-chart
  when:
    event:
      - tag

- name: release
  image: harbor.winters.org.nz/hub-cache/library/ubuntu:20.04
  commands:
    - echo "Starting Release Build"
  depends_on:
    - build-release-docker-image
    - build-release-chart
  when:
    event:
      - tag

- name: dev
  image: harbor.winters.org.nz/hub-cache/library/alpine:latest
  commands:
  - echo "Starting Dev Build"
  depends_on:
    - build-dev-docker-image
  when:
    event:
      include:
        - push
      exclude:
        - tag