with-expecter: True
inpackage: True
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }} 
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  github.com/influxdata/influxdb-client-go/v2:
    config:
      recursive: True
  github.com/mwinters-stuff/solar-zero-scrape-golang/solarzero:
    config:
      recursive: True
      all: True