// Code generated by go-swagger; DO NOT EDIT.

package http_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPanicOKCode is the HTTP code returned for type GetPanicOK
const GetPanicOKCode int = 200

/*
GetPanicOK OK

swagger:response getPanicOK
*/
type GetPanicOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetPanicOK creates GetPanicOK with default headers values
func NewGetPanicOK() *GetPanicOK {

	return &GetPanicOK{}
}

// WithPayload adds the payload to the get panic o k response
func (o *GetPanicOK) WithPayload(payload string) *GetPanicOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get panic o k response
func (o *GetPanicOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPanicOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
