// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	middleware "github.com/go-openapi/runtime/middleware"
	kubernetes "github.com/mwinters-stuff/solar-zero-scrape-golang/api/restapi/operations/kubernetes"

	mock "github.com/stretchr/testify/mock"
)

// GetHealthzHandlerFunc is an autogenerated mock type for the GetHealthzHandlerFunc type
type GetHealthzHandlerFunc struct {
	mock.Mock
}

type GetHealthzHandlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *GetHealthzHandlerFunc) EXPECT() *GetHealthzHandlerFunc_Expecter {
	return &GetHealthzHandlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *GetHealthzHandlerFunc) Execute(_a0 kubernetes.GetHealthzParams) middleware.Responder {
	ret := _m.Called(_a0)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(kubernetes.GetHealthzParams) middleware.Responder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}

// GetHealthzHandlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetHealthzHandlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//  - _a0 kubernetes.GetHealthzParams
func (_e *GetHealthzHandlerFunc_Expecter) Execute(_a0 interface{}) *GetHealthzHandlerFunc_Execute_Call {
	return &GetHealthzHandlerFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *GetHealthzHandlerFunc_Execute_Call) Run(run func(_a0 kubernetes.GetHealthzParams)) *GetHealthzHandlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubernetes.GetHealthzParams))
	})
	return _c
}

func (_c *GetHealthzHandlerFunc_Execute_Call) Return(_a0 middleware.Responder) *GetHealthzHandlerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewGetHealthzHandlerFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetHealthzHandlerFunc creates a new instance of GetHealthzHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetHealthzHandlerFunc(t mockConstructorTestingTNewGetHealthzHandlerFunc) *GetHealthzHandlerFunc {
	mock := &GetHealthzHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
