// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	middleware "github.com/go-openapi/runtime/middleware"
	kubernetes "github.com/mwinters-stuff/solar-zero-scrape-golang/restapi/operations/kubernetes"

	mock "github.com/stretchr/testify/mock"
)

// GetHealthzHandler is an autogenerated mock type for the GetHealthzHandler type
type GetHealthzHandler struct {
	mock.Mock
}

type GetHealthzHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *GetHealthzHandler) EXPECT() *GetHealthzHandler_Expecter {
	return &GetHealthzHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0
func (_m *GetHealthzHandler) Handle(_a0 kubernetes.GetHealthzParams) middleware.Responder {
	ret := _m.Called(_a0)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(kubernetes.GetHealthzParams) middleware.Responder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}

// GetHealthzHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type GetHealthzHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//  - _a0 kubernetes.GetHealthzParams
func (_e *GetHealthzHandler_Expecter) Handle(_a0 interface{}) *GetHealthzHandler_Handle_Call {
	return &GetHealthzHandler_Handle_Call{Call: _e.mock.On("Handle", _a0)}
}

func (_c *GetHealthzHandler_Handle_Call) Run(run func(_a0 kubernetes.GetHealthzParams)) *GetHealthzHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubernetes.GetHealthzParams))
	})
	return _c
}

func (_c *GetHealthzHandler_Handle_Call) Return(_a0 middleware.Responder) *GetHealthzHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewGetHealthzHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetHealthzHandler creates a new instance of GetHealthzHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetHealthzHandler(t mockConstructorTestingTNewGetHealthzHandler) *GetHealthzHandler {
	mock := &GetHealthzHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
