// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	middleware "github.com/go-openapi/runtime/middleware"
	kubernetes "github.com/mwinters-stuff/solar-zero-scrape-golang/restapi/operations/kubernetes"

	mock "github.com/stretchr/testify/mock"
)

// GetMetricsHandlerFunc is an autogenerated mock type for the GetMetricsHandlerFunc type
type GetMetricsHandlerFunc struct {
	mock.Mock
}

type GetMetricsHandlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *GetMetricsHandlerFunc) EXPECT() *GetMetricsHandlerFunc_Expecter {
	return &GetMetricsHandlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *GetMetricsHandlerFunc) Execute(_a0 kubernetes.GetMetricsParams) middleware.Responder {
	ret := _m.Called(_a0)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(kubernetes.GetMetricsParams) middleware.Responder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}

// GetMetricsHandlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetMetricsHandlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//  - _a0 kubernetes.GetMetricsParams
func (_e *GetMetricsHandlerFunc_Expecter) Execute(_a0 interface{}) *GetMetricsHandlerFunc_Execute_Call {
	return &GetMetricsHandlerFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *GetMetricsHandlerFunc_Execute_Call) Run(run func(_a0 kubernetes.GetMetricsParams)) *GetMetricsHandlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(kubernetes.GetMetricsParams))
	})
	return _c
}

func (_c *GetMetricsHandlerFunc_Execute_Call) Return(_a0 middleware.Responder) *GetMetricsHandlerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewGetMetricsHandlerFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetMetricsHandlerFunc creates a new instance of GetMetricsHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetMetricsHandlerFunc(t mockConstructorTestingTNewGetMetricsHandlerFunc) *GetMetricsHandlerFunc {
	mock := &GetMetricsHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
