// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	middleware "github.com/go-openapi/runtime/middleware"
	http_api "github.com/mwinters-stuff/solar-zero-scrape-golang/restapi/operations/http_api"

	mock "github.com/stretchr/testify/mock"
)

// GetPanicHandlerFunc is an autogenerated mock type for the GetPanicHandlerFunc type
type GetPanicHandlerFunc struct {
	mock.Mock
}

type GetPanicHandlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *GetPanicHandlerFunc) EXPECT() *GetPanicHandlerFunc_Expecter {
	return &GetPanicHandlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *GetPanicHandlerFunc) Execute(_a0 http_api.GetPanicParams) middleware.Responder {
	ret := _m.Called(_a0)

	var r0 middleware.Responder
	if rf, ok := ret.Get(0).(func(http_api.GetPanicParams) middleware.Responder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(middleware.Responder)
		}
	}

	return r0
}

// GetPanicHandlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type GetPanicHandlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//  - _a0 http_api.GetPanicParams
func (_e *GetPanicHandlerFunc_Expecter) Execute(_a0 interface{}) *GetPanicHandlerFunc_Execute_Call {
	return &GetPanicHandlerFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *GetPanicHandlerFunc_Execute_Call) Run(run func(_a0 http_api.GetPanicParams)) *GetPanicHandlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http_api.GetPanicParams))
	})
	return _c
}

func (_c *GetPanicHandlerFunc_Execute_Call) Return(_a0 middleware.Responder) *GetPanicHandlerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewGetPanicHandlerFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetPanicHandlerFunc creates a new instance of GetPanicHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetPanicHandlerFunc(t mockConstructorTestingTNewGetPanicHandlerFunc) *GetPanicHandlerFunc {
	mock := &GetPanicHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
