// Code generated by mockery v2.35.1. DO NOT EDIT.

package solarzero

import mock "github.com/stretchr/testify/mock"

// MQTTClient is an autogenerated mock type for the MQTTClient type
type MQTTClient struct {
	mock.Mock
}

type MQTTClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MQTTClient) EXPECT() *MQTTClient_Expecter {
	return &MQTTClient_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields:
func (_m *MQTTClient) Connect() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MQTTClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MQTTClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MQTTClient_Expecter) Connect() *MQTTClient_Connect_Call {
	return &MQTTClient_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MQTTClient_Connect_Call) Run(run func()) *MQTTClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MQTTClient_Connect_Call) Return(_a0 error) *MQTTClient_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MQTTClient_Connect_Call) RunAndReturn(run func() error) *MQTTClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// WriteCurrentData provides a mock function with given fields: scrape
func (_m *MQTTClient) WriteCurrentData(scrape SolarZeroScrape) {
	_m.Called(scrape)
}

// MQTTClient_WriteCurrentData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteCurrentData'
type MQTTClient_WriteCurrentData_Call struct {
	*mock.Call
}

// WriteCurrentData is a helper method to define mock.On call
//   - scrape SolarZeroScrape
func (_e *MQTTClient_Expecter) WriteCurrentData(scrape interface{}) *MQTTClient_WriteCurrentData_Call {
	return &MQTTClient_WriteCurrentData_Call{Call: _e.mock.On("WriteCurrentData", scrape)}
}

func (_c *MQTTClient_WriteCurrentData_Call) Run(run func(scrape SolarZeroScrape)) *MQTTClient_WriteCurrentData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(SolarZeroScrape))
	})
	return _c
}

func (_c *MQTTClient_WriteCurrentData_Call) Return() *MQTTClient_WriteCurrentData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MQTTClient_WriteCurrentData_Call) RunAndReturn(run func(SolarZeroScrape)) *MQTTClient_WriteCurrentData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteData provides a mock function with given fields: scrape
func (_m *MQTTClient) WriteData(scrape SolarZeroScrape) {
	_m.Called(scrape)
}

// MQTTClient_WriteData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteData'
type MQTTClient_WriteData_Call struct {
	*mock.Call
}

// WriteData is a helper method to define mock.On call
//   - scrape SolarZeroScrape
func (_e *MQTTClient_Expecter) WriteData(scrape interface{}) *MQTTClient_WriteData_Call {
	return &MQTTClient_WriteData_Call{Call: _e.mock.On("WriteData", scrape)}
}

func (_c *MQTTClient_WriteData_Call) Run(run func(scrape SolarZeroScrape)) *MQTTClient_WriteData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(SolarZeroScrape))
	})
	return _c
}

func (_c *MQTTClient_WriteData_Call) Return() *MQTTClient_WriteData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MQTTClient_WriteData_Call) RunAndReturn(run func(SolarZeroScrape)) *MQTTClient_WriteData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteDayData provides a mock function with given fields: scrape
func (_m *MQTTClient) WriteDayData(scrape SolarZeroScrape) {
	_m.Called(scrape)
}

// MQTTClient_WriteDayData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteDayData'
type MQTTClient_WriteDayData_Call struct {
	*mock.Call
}

// WriteDayData is a helper method to define mock.On call
//   - scrape SolarZeroScrape
func (_e *MQTTClient_Expecter) WriteDayData(scrape interface{}) *MQTTClient_WriteDayData_Call {
	return &MQTTClient_WriteDayData_Call{Call: _e.mock.On("WriteDayData", scrape)}
}

func (_c *MQTTClient_WriteDayData_Call) Run(run func(scrape SolarZeroScrape)) *MQTTClient_WriteDayData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(SolarZeroScrape))
	})
	return _c
}

func (_c *MQTTClient_WriteDayData_Call) Return() *MQTTClient_WriteDayData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MQTTClient_WriteDayData_Call) RunAndReturn(run func(SolarZeroScrape)) *MQTTClient_WriteDayData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMonthData provides a mock function with given fields: scrape
func (_m *MQTTClient) WriteMonthData(scrape SolarZeroScrape) {
	_m.Called(scrape)
}

// MQTTClient_WriteMonthData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMonthData'
type MQTTClient_WriteMonthData_Call struct {
	*mock.Call
}

// WriteMonthData is a helper method to define mock.On call
//   - scrape SolarZeroScrape
func (_e *MQTTClient_Expecter) WriteMonthData(scrape interface{}) *MQTTClient_WriteMonthData_Call {
	return &MQTTClient_WriteMonthData_Call{Call: _e.mock.On("WriteMonthData", scrape)}
}

func (_c *MQTTClient_WriteMonthData_Call) Run(run func(scrape SolarZeroScrape)) *MQTTClient_WriteMonthData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(SolarZeroScrape))
	})
	return _c
}

func (_c *MQTTClient_WriteMonthData_Call) Return() *MQTTClient_WriteMonthData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MQTTClient_WriteMonthData_Call) RunAndReturn(run func(SolarZeroScrape)) *MQTTClient_WriteMonthData_Call {
	_c.Call.Return(run)
	return _c
}

// WriteYearData provides a mock function with given fields: scrape
func (_m *MQTTClient) WriteYearData(scrape SolarZeroScrape) {
	_m.Called(scrape)
}

// MQTTClient_WriteYearData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteYearData'
type MQTTClient_WriteYearData_Call struct {
	*mock.Call
}

// WriteYearData is a helper method to define mock.On call
//   - scrape SolarZeroScrape
func (_e *MQTTClient_Expecter) WriteYearData(scrape interface{}) *MQTTClient_WriteYearData_Call {
	return &MQTTClient_WriteYearData_Call{Call: _e.mock.On("WriteYearData", scrape)}
}

func (_c *MQTTClient_WriteYearData_Call) Run(run func(scrape SolarZeroScrape)) *MQTTClient_WriteYearData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(SolarZeroScrape))
	})
	return _c
}

func (_c *MQTTClient_WriteYearData_Call) Return() *MQTTClient_WriteYearData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MQTTClient_WriteYearData_Call) RunAndReturn(run func(SolarZeroScrape)) *MQTTClient_WriteYearData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMQTTClient creates a new instance of MQTTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMQTTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MQTTClient {
	mock := &MQTTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
