// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Solar Zero Scrape API
//
//	Solar Sero Scrape.
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 2.0
//	License: Apache License https://gitea.winters.org.nz/mathew/solar-zero-scrape-golang/src/branch/master/LICENSE
//	Contact: Source Code https://gitea.winters.org.nz/mathew/solar-zero-scrape-golang
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
