---
apiVersion: v2
appVersion: 1.0.0
description: An image and helm chart for solar-zero-scrape
name: solar-zero-scrape
version: 2.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - solar-zero-scrape
home: https://github.com/mwinters-stuff/solar-zero-scrape
sources:
  - https://github.com/mwinters-stuff/solar-zero-scrape
maintainers:
  - name: mwinters
    email: mathew@winters.nz
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
