---
apiVersion: v2
appVersion: 4.0.4
description: An image and helm chart for solar-zero-scrape
name: solar-zero-scrape
version: 4.0.4
kubeVersion: ">=1.16.0-0"
keywords:
  - solar-zero-scrape
home: https://github.com/mwinters-stuff/solar-zero-scrape
sources:
  - https://github.com/mwinters-stuff/solar-zero-scrape
maintainers:
  - name: mwinters
    email: mathew@winters.nz
# dependencies:
#   - name: common
#     repository: http://harbor.harbor.svc/chartrepo/k8s-at-winters
#     version: latest
