#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: harbor.winters.org.nz/library/solar-zero-scrape
  # -- image tag
  tag: "latest"
  # -- image pull policy
  pullPolicy: IfNotPresent

nameOverride: "solar-zero-scrape"
fullnameOverride: "solar-zero-scrape"


# @default -- See below
env:
  # -- Set the container timezone
  TZ: Pacific/Auckland

#-- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: false

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence, config for where the yaml and custom script live..
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: configMap
    name: solar-zero-scrape-config


configmap:
  config:
    enabled: true
    data:
      solar-zero-scrape.json: |
        {
          "DebugLog":"debug.log",
          "SolarZero": {
              "Username": "your@email",
              "Password": "password",
              "UserPoolId": "us-west-2_NoMpv1v1A",
              "ClientId": "6mgtqq7vvf7eo3r3qrsg6kl1tf",
              "API": {
                "Region" :"us-west-2",
                "ApiGatewayURL": "https://d6nfzye2cb.execute-api.us-west-2.amazonaws.com",
                "ApiKey": "mA0UW2ldUUQBY3e9bZWq9lCeKQUNCZC9oKidvdbb",
                "SolarZeroApiAddress": "solarzero.pnz.technology"
              }
          },
          "InfluxDB":{
              "Token": "token",
              "HostUrl": "https://influxdb.example.com",
              "Org": "example.com",
              "Bucket": "solarzero/autogen"
          },
          "MQTT": {
            "URL":"mqtt://example.com:1883",
            "Username": "solarzero",
            "Password": "zerosolar",
            "BaseTopic":"solar-zero"
          }
        }