// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// APIMapResponse api map response
//
// swagger:model api.MapResponse
type APIMapResponse map[string]string

// Validate validates this api map response
func (m APIMapResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api map response based on context it is used
func (m APIMapResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
